### ISSUE TITLE
Deploys should not implement any missing custom database scripts

### ISSUE THREAD

**Issue by rolodato** [auth0-extensions/auth0-github-deploy#14]
Auth0 will always execute the `get_user` script if implemented, where "implemented" is defined as "`get_user` property exists on the database connection object". This can cause issues for scenarios where it's not expected to have these scripts implemented, e.g. when "import users" is disabled.

The extension should not set defaults for any database scripts that are not implemented. It should not set them in the connection object at all.

**Comment by zxan1285** [comment]
Fixed in source-control-tools
