### ISSUE TITLE
Silent failure if a rule is created with a bad rulename

### ISSUE THREAD

**Issue by mostekcm** [auth0-extensions/auth0-github-deploy#15]
Steps to replicate:
0) Enable realtime webtask logs
1) Enable github extensions
2) Create repo with rules/console_log.js and rules/console_log.json in them
3) push repo
4) Github extensions page will say successful deployment
5) realtime webtask logs show failure

Expected:
4) should be a failed deployment

**Comment by zxan1285** [comment]
Fixed in source-control-tools
