### ISSUE TITLE
Error with uglify and ES6 syntax

### ISSUE THREAD

**Issue by sgmeyer** [auth0-extensions/auth0-github-deploy#20]
It seems there is an issue with express-conditional-middleware causing issues with uglify.  It appears the express-conditionals-middleware uses ES6 syntax that is causing issues during `npm run build`.

![image](https://cloud.githubusercontent.com/assets/1427318/23727250/e0783e5a-041c-11e7-96bb-84857a4a5328.png)

I believe this code is the culprit:

```
// node_modules/express-conditional-middleware/lib/condition.js
module.exports = (condition, success, fail) => (req, res, next) => {
  const nextOnce = once(next);
  if (condition === true || (typeof condition === 'function' && condition(req, res, nextOnce))) {
    return success(req, res, nextOnce);
  }
  if (fail) {
    return fail(req, res, nextOnce);
  }

  return nextOnce();
};
```

if this is changed to functions instead of () => everything seems to play nice with building.

**Comment by sandrinodm** [comment]
Solved here: https://github.com/auth0-extensions/auth0-github-deploy/blob/master/build/extension/webpack.config.js#L80
