### ISSUE TITLE
Unable to clear the manual flag from all rules

### ISSUE THREAD

**Issue by jmangelo** [auth0-extensions/auth0-github-deploy#22]
Steps to reproduce:

1. Select one or more rules as manual and click the update button.
1. Deselect all the previously selected rules and click the update button.

Expected:
None of the rules would be marked as manual.

Actual:
If you refresh, the rules will still be flagged as manual because when you try to clear the manual flag from all rules at once the update button does not trigger any update on the back-end.

As additional information, this problem will likely affect all other deploy related extensions as they use the same logic for this screen, more specifically, the problem seems to be caused by:

https://github.com/auth0-extensions/auth0-github-deploy/blob/master/client/components/RulesTable.jsx#L40

**Comment by zxan1285** [comment]
Fixed in #23
