### ISSUE TITLE
Add Email Template Support

### ISSUE THREAD

**Issue by troyschneringer** [auth0-extensions/auth0-github-deploy#25]
This has been a great addition for managing scripts for connections and rules.  It would be great to see something added for Email Templates as well.

**Comment by johnlim** [comment]
Is there any timeline or update for this? Thanks.

**Comment by dctoon** [comment]
I have taken note of the feature, but we don't have short term plans to add this functionality.

**Comment by abbaspour** [comment]
[forked auth0-source-control-extension-tools](https://github.com/abbaspour/auth0-source-control-extension-tools/tree/feature/email-template) to add email template.

**Comment by abbaspour** [comment]
@dctoon would u plz assign this ticket to me.

**Comment by sandeepasrani** [comment]
Hey, 

I just wanted to check-in if there is any update on this. This feature sounds like a good promise to have everything close to the source and we can avoid making changes by hand.

**Comment by rhanton** [comment]
So is this not happening?
