### ISSUE TITLE
Login failed. State mismatch

### ISSUE THREAD

**Issue by salmanm** [auth0-extensions/auth0-github-deploy#26]
I am using auth0 enterprise and installed this extension. I configured github details and then authenticated myself on the extension. But then I don't see extension dashboard, I see this error 

```
{"error":"ValidationError","message":"Login failed. State mismatch."}
```

**Comment by sgmeyer** [comment]
ACK.  I was able to reproduce this.  I am still trying to figure out what is causing it, but will give it a look.
