### ISSUE TITLE
For my tenant, manual deploy works from the button but it does not deploy automatically on merge to master.

### ISSUE THREAD

**Issue by aonamrata** [auth0-extensions/auth0-github-deploy#49]
I followed the steps from https://auth0.com/docs/extensions/github-deploy
and got my deploy working manually. But it does not do it automatically. Do anyone know what can be the issue?

**Comment by fyockm** [comment]
@aonamrata did you setup the webhooks in Github as described in the document you linked?

**Comment by aonamrata** [comment]
ah yes. We can close this.. it was some config change on the webhook that got it working.
