### ISSUE TITLE
Connection update not working

### ISSUE THREAD

**Issue by renesnezic** [auth0-extensions/auth0-github-deploy#57]
When specifying a connection (connections folder) it only works when the connection does not exist yet. Once it has been created, redeploying will fail. Meaning there is no proper check in place to verify if connection exists - thus updating it.

The error returned:
APIError: {"statusCode":409,"error":"Conflict","message":"A connection with the same name already exists","errorCode":"connection_conflict"}

This is a very important thing as deploying a client will disable it under the connection and we would like to specify the enabled_clients to prevent breaking our Auth0 with just a re-deploy.

**Comment by renesnezic** [comment]
Looking at the source code of auth0-source-control-extension-tools it seems all connections with 'auth0' strategy get filtered out of existing connections. What is the point of this? I'll test out if using a different strategy, maybe 'custom' will not break any other functionality we might need on our connection.

https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/connections.js#L37

**Comment by ShayMe21** [comment]
Hey, can you paste the file/folder structure you are using as well as the contents of the file(s)? Also what version of the extension are you currently using?

Following the documentation [here](https://auth0.com/docs/extensions/github-deploy#deployment), I was able to create and update a custom database connection `login.js` file.

Please list the reproduction steps for us so we can investigate.

**Comment by renesnezic** [comment]
Current folder structure:
├── clients
│   ├── Mobile App.json
│   └── Server API App.json
├── connections
│   └── Source.json
├── database-connections
│   └── Source
│       ├── get_user.js
│       └── login.js
├── README.md
├── resource-servers
│   └── Basic API.json
└── rules
    ├── add-data-to-access-token.js
    ├── add-data-to-access-token.json
    ├── add-data-to-id-token.js
    ├── add-data-to-id-token.json
    ├── update-metadata.js
    ├── update-metadata.json
    ├── verify-env.js
    └── verify-env.json

On the same documentation page you posted, there is a chapter regarding [connections](https://auth0.com/docs/extensions/github-deploy#deploy-connections).

Steps to reproduce:
1. Create database connection using:
    a) web
    b) management API with strategy 'auth0'
    c) github deployment using folder 'connections' and in the json specifying the strategy as 'auth0'
2. Create folder 'connections' and json file specifying connection settings as in the documentation (if not done in step 1) - keeping in mind to use the same name as in step 1
3. Run github deployment (at this point the deployment fails)

Also may I point it is very strange there is a "connections" section in the auth0 Documentation but not in this repository README file.

**Comment by ShayMe21** [comment]
Thanks for explaining that. I was able to reproduce this error as well. It seems like updating a connection that already exists throws a `409`.

**Comment by zxan1285** [comment]
Hi. In the latest version (2.6) of the extension you can update auth0 connection (strategy: auth0) by adding `database-connections/[connection-name]/setting.json`. `connections` dir is for non-auth0 connections.
We're working on updating the docs.

**Comment by fyockm** [comment]
please see https://github.com/auth0/docs/pull/7214
