### ISSUE TITLE
Please keep changelog up to date

### ISSUE THREAD

**Issue by goodspark** [auth0-extensions/auth0-github-deploy#58]
The version available in auth0 is now 2.6, but there is no release, no tag, and no changelog for 2.6.

**Comment by fyockm** [comment]
hi @goodspark - a couple things. with the `2.6` release of this extension, we have moved from separate repositories for each the deployment extensions (github, gitlab, bitbucket, and vsts) to building via a single [`auth0-deploy-extensions` monorepo](https://github.com/auth0-extensions/auth0-deploy-extensions). this will make them much easier to maintain and keep track of fixes across all four extensions. this repo will be marked as read-only very soon.

That said, we **are** currently lacking a changelog in the new monorepo, and will remedy.

Aside from a new build process, the one notable change for `auth0-github-deploy@2.6` is:
https://github.com/auth0-extensions/auth0-github-deploy/pull/56

**Comment by goodspark** [comment]
Cool! Thank you
