### ISSUE TITLE
Provide a means to deploy encrypted secrets for rules and DB scripts

### ISSUE THREAD

**Issue by goodspark** [auth0-extensions/auth0-github-deploy#59]
I'd like to keep all my configuration and secrets in version control to minimize human error when updating auth0 settings.

Obviously we shouldn't store secrets in plain text. So that leaves encryption.

Something like [sops](https://github.com/mozilla/sops) or similar would be perfect.

**Comment by fyockm** [comment]
@goodspark would you mind closing this issue and reopening on the auth0-deploy-extensions repo?

https://github.com/auth0-extensions/auth0-deploy-extensions/issues/new

**Comment by goodspark** [comment]
Sure! Thanks
